2018-02-05 18:39:18,396 ERROR division by zero
Traceback (most recent call last):
  File "D:/dev/workspace/django/loop_server/x8.py", line 28, in <module>
    3/0
ZeroDivisionError: division by zero
2018-02-06 09:34:48,023 ERROR division by zero
Traceback (most recent call last):
  File "D:/dev/workspace/django/loop_server/x8.py", line 28, in <module>
    3/0
ZeroDivisionError: division by zero
